### ISSUE TITLE
Pressing "finish" after a successful release causes an error

### ISSUE THREAD

**Issue by cmfcmf** [zikula/CoreManagerModule#16]
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Error: Call to a member function getName() on a non-object
```

**Comment by craigh** [comment]
would have to work with `debug: true` to get the full trace here, but I would gamble that you have a module (News?) that isn't namespaced and therefore not available as an object or have somehow not instantiated a proper module.

**Comment by craigh** [comment]
just experienced this with release of core-1.4.2. Therefore, no article was published at all - not even pending :cry:

**Comment by craigh** [comment]
`Fatal error: Call to a member function getName() on a non-object in /home/zwww/core/src/modules/zikula/coremanager-module/Controller/ReleaseController.php on line 63`
ping @cmfcmf

**Comment by craigh** [comment]
I was able to overcome the bug by reloading core releases from the admin.
