### ISSUE TITLE
Newly created Jenkins Job doesn't do anything until being disabled and enabled again

### ISSUE THREAD

**Issue by cmfcmf** [zikula/CoreManagerModule#18]

**Comment by craigh** [comment]
@Guite maybe knows enough about Jenkins to help?

**Comment by craigh** [comment]
I didn't test this but read it and enabled/disabled the job before attempting a new build.

**Comment by craigh** [comment]
ping @Guite this requires your expertise.

**Comment by Guite** [comment]
No idea about that, sorry.

**Comment by Guite** [comment]
This can very probably be closed now, since branches/jobs are automatically managed as sub jobs of the primary multibranch job in Jenkins.
