### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by craigh** [zikula/CoreManagerModule#25]
received OutOfMemoryException when attempting Core-2.0-RC1

@cmfcmf ideas?

![screen shot 2017-07-20 at 10 42 32 am](https://user-images.githubusercontent.com/350048/28423213-707454ec-6d38-11e7-8fdb-f8e0de6341d4.png)

**Comment by cmfcmf** [comment]
Hmm, no :(

**Comment by craigh** [comment]
probably we need to start some kind of process that detaches itself from the http process so that it will keep running. 

maybe we can prefix it with something like `php -dmemory_limit=2G`

**Comment by Guite** [comment]
The current workaround is working. Should we nevertheless aim for a better (and more complex) solution?
