### ISSUE TITLE
Get News integration working.. finally...

### ISSUE THREAD

**Issue by cmfcmf** [zikula/CoreManagerModule#4]
Also, the Release is not updated with the copied Jenkins assets.

**Comment by cmfcmf** [comment]
Also there shouldn't be a timelimit set. https://github.com/zikula/CoreManagerModule/blob/master/Manager/ReleaseManager.php#L655-L657

**Comment by craigh** [comment]
I haven't look at this in a long time, but here is the hook connection between news and PC

https://github.com/craigh/PostCalendar/blob/master/lib/PostCalendar/PostCalendarEvent/News.php

hmm, I took a quick look at the table row and I think all you can do to accommodate the TZ problem is get a time from the server or something and compute the time required. I think the 'published' status is derived only from the post-datetime

@espaan

**Comment by Guite** [comment]
Closed as the News integration has been rewritten.
